### ISSUE TITLE
ProgressLogger should have a `record(rec: AlignedSegment)` function

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgpyo#31]
Because progress logger wants 1-based coordinates and AlignedSegments use zero-based coordinates, this makes correct use clunky, e.g.:

```python
if rec.reference_start is not None:
    progress.record(rec.reference_name, rec.reference_start + 1)
else:
    progress.record()
```

If you don't do this, and you happen to hit a logging threshold when the last reference start is `0` the progress logger will raise an assertion error!

**Comment by sam-white04** [comment]
@tfenne I am just getting into this, but for clarification are you suggesting added functionality to ProgressLogger.record() or a new function entirely?

**Comment by nh13** [comment]
Since you can't have multiple functions with the same name, you have two options:

1. Create two differently named methods.  You would keep the `def record` as is, but have a separate `def record_alignment` or the like that itself calls the `record` method.
2. Have all the arguments be optional to the single `def record` method.  In this case, add a fourth parameter (e.g. `record: Optional[AlignedSegment] = None`).  In this case, you should verify (assert) that either reference_name/position are given, or `record` is given, but not both.  Then you can use the one that is defined (i.e. not `None`)

Perhaps the next step for @sam-white04 is to brainstorm the tradeoffs in a detailed manner from the perspective of the API user and implementation (we can do so over Slack), then pick one to implement?

**Comment by sam-white04** [comment]
@nh13 I think I prefer option 2 listed above, but I will outline the tradeoffs as you suggested and share that with you over slack.

**Comment by sam-white04** [comment]
@nils I have slacked you and @tim regarding the options outlined above

**Comment by sam-white04** [comment]
@nils here is an example for solution 1 - [record_alignment()](https://github.com/fulcrumgenomics/fgpyo/blob/issue_31_v2/fgpyo/util/logging.py)
here is an example for solution 2 - [optional arguments](https://github.com/fulcrumgenomics/fgpyo/blob/issue_31/fgpyo/util/logging.py)

**Comment by nh13** [comment]
Lets just go with `record_alignment` for now.

**Comment by sam-white04** [comment]
@nh13 great, I will make a PR. Thanks!

**Comment by clintval** [comment]
Closed by: https://github.com/fulcrumgenomics/fgpyo/pull/33
